---
title: "Joins and strings and dates"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)
```

## Joins

```{r}
animals <- tibble::tribble(
             ~location,   ~species,  ~maturity,
              "lagoon",   "bobcat",    "adult",
               "bluff",   "coyote", "juvenile",
               "creek",      "fox",    "adult",
                "oaks", "squirrel", "juvenile",
               "bluff",   "bobcat",    "adult"
             )

sites <- tibble::tribble(
           ~location,      ~full_site_name, ~jurisdiction,
             "beach",       "Goleta Beach",     "SB City",
            "lagoon",        "UCSB Lagoon",        "UCSB",
             "bluff",       "Ellwood Mesa",     "SB City",
              "oaks", "Fremont Campground",        "USFS"
           )

```

### Full Join

```{r}
# if not specified it will use the column names to find a matching key 
# can specify the matching key using by = 
full_join_example <- full_join(animals, sites, by = "location")
```

### Left Join

```{r}
left_join_example <- left_join(animals, sites, by = "location")
```

### Inner Join

```{r}
inner_join_example <- inner_join(animals, sites, by = "location")
```

```{r}
sites_2 <- sites |> 
  rename(loc = location)
```

Example of joining when key variables have non-matching names

```{r}
nonmatching <- full_join(animals, sites_2, by = c("location" = "loc"))
```

### Semi Join

```{r}
semi_join_example <- semi_join(animals, sites, by = "location")
```

### Anti join

```{r}
anti_join_example <- anti_join(animals, sites, by = "location")
```

Refresher 1 Practice

```{r}
penguins_filtered <- penguins |> 
  filter(island %in% c("Biscoe", "Dream")) |> 
  select(-year, -sex) |> 
  mutate(body_mass_kg = body_mass_g/1000) |> 
  rename(location = island)
```

## Dates and times with `lubridate`

```{r}
my_date <- "03-15-1998"

# define order mdy, ymd, dmy
lubridate::mdy(my_date)

my_date <- "11/7/2003"
lubridate::dmy(my_date)

my_date <- "08-Jun-1974"
lubridate::dmy(my_date)

my_date <- "19610518"
my_real_date <- lubridate::ymd(my_date)
```

```{r}
lubridate::ymd("1942-08-30")

lubridate::mdy("09/22/84")
```

```{r}
time <- "2020-08-12 11:18"
time <- ymd_hm(time)
time
class(time)
# class of data with time in it will be POSIXct, class of data with only dates will be date
```

```{r}
# use with_tz to convert time zones
with_tz(time, "America/Los_Angeles")

with_tz(time, "Indian/Maldives")

with_tz(time, "Europe/Paris")

my_time <- lubridate::ymd_hms(time)

# Parse out individual components of your date time value
year(my_time)
day(my_time)
month(my_time)
hour(my_time)
minute(my_time)
second(my_time)
```

```{r}
teddy_bday <- lubridate::ymd("20170615")

# what day of the week is your date
wday(teddy_bday, label = TRUE)

my_birthday <- lubridate::ymd("1995-07-07")
wday(my_birthday, label = TRUE)

# what week of the year
week(teddy_bday)
week(my_birthday)
```

```{r}
# create a data set
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

# convert the date values to ISO 6801 (date class), pull out year, month, and day and add them as separate columns and store it in another data set named urchin_ymd
urchin_ymd <- urchin_counts |> 
  mutate(date = mdy(date)) |> 
  mutate(year = year(date),
         month = month(date),
         day = day(date))
```

```{r}
day_1 <- ymd("2020-01-06")
day_2 <- ymd("2020-05-18")

# create the interval between the two dates and store it as time_interval
time_interval <- interval(day_1, day_2)

# in years, what is the length of the time interval
time_length(time_interval, "year")

# in days, what is the length of the time interval
time_length(time_interval, "day")

# in seconds, what is the length of the time interval
time_length(time_interval, "second")
```

## stringr for working with strings

### str_detect

```{r}
my_string <- "Teddy loves eating salmon and socks."

my_string |> 
  str_detect("love")

my_string |> 
  str_detect("pup")

my_string <- c("burrito", "fish taco", "taco salad")
my_string |> 
  str_detect("fish")
```

```{r}
# from the star wars data frome, only keep rows where the pattern Skywalker exists in the name column
skywalkers <- starwars |> 
  filter(str_detect(name, pattern = "Skywalker"))

# create a subset where Maul shows up in the name column
maul <- starwars |> 
  filter(str_detect(name, pattern = "Maul"))

# create a subset where blue shows up in the eye color, either alone or in combination
# these are case senstitive
blue_eyes <- starwars |> 
  filter(str_detect(eye_color, pattern = "blue"))

```

### str_repalce to replace string patterns

```{r}
firewalkers <- starwars |> 
  mutate(name_2 = str_replace(name, pattern = "Sky", replacement = "Fire"))
```

```{r}
feedback <- c("  I ate  some  nachos", "Wednesday   morning  ")
# str_trim removes excess white space before first character and after last character in a string
str_trim(feedback)

# str_squish removes excess white space before first character and after last character in a string AND in between words
str_squish(feedback)

# str_to*
# all lower case
str_to_lower(feedback)

# all upper case
str_to_upper(feedback)

# first letter of word is capitalized
str_to_title(feedback)

# follow sentence structure with first word first letter capitalized
str_to_sentence(feedback)


# From star wars, create a new data frame starwars_lc that adds a new column called name_lower containing character names converted to all lowercase
starwars_lc <- starwars |> 
  mutate(name_lower = str_to_lower(name))
```

### case_when()

```{r}
# create a new column that outputs different values based on the corresponding value in the species column using case_when()
starwars_robot <- starwars |> 
  mutate(robot_status = case_when(
    species == "Droid" ~ "A ROBOT!!!",
    species == "Human" ~ "It's a human!",
    TRUE ~ "This is something else."
  ))
```
